name: varialbles
run-name:  Aprender a usar las Variables de Entorno
on: [push, pull_request]
env:
  fruta1: Manzana
  fruta2: Pera
  fruta3: Frutilla
jobs:
  Variables:
    runs-on: ubuntu-latest
    steps:
      - name: echo frutas
        run: echo "La $fruta1 es roja, la $fruta2 es verde, la $fruta3 es roja y el ${{ vars.ENV_NAME }} es amarillo ${{ github.repository }} - NOMBRE: $NOMBRE"
        env: 
          NOMBRE: "Jorge"